services:

  backend:
    build:
      context: ./backend
    container_name: rifle-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    command: sh -c "npm install && npx prisma generate --schema=src/prisma/schema.prisma && npm run dev"

  frontend:
    build:
      context: ./frontend
    container_name: rifle-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
  
  mobile:
    build:
      context: ./mobile
    container_name: rifle-mobile
    environment:
     - EXPO_PUBLIC_API_URL=http://rifle-backend:3000/api
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    volumes:
      - ./mobile:/app
      - mobile_modules:/app/node_modules
    command: npx expo start --tunnel --clear

  db:
    image: postgres:15
    container_name: rifle-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rifle_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: rifle-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  backend_modules:
  frontend_modules:
  mobile_modules: